version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.3
  pagerduty: amanjain97/pagerduty@dev:alpha

jobs:
  incident-on-success:
    executor: orb-tools/ubuntu
    steps:
    - run: exit 0 #toggle this to force success or status for testing
    - pagerduty/notify-on-failure:
        service: "PB63G5C"
        from_account: "amanjain5221@gmail.com"

  incident-on-fail:
    executor: orb-tools/ubuntu
    steps:
    - run: exit 1  #toggle this to force success or status for testing
    - pagerduty/notify-on-failure:
        service: "PB63G5C"
        from_account: "amanjain5221@gmail.com"


workflows:
  test_pagerduty:
    jobs:
      - incident-on-success
      - incident-on-fail